Optimize json encoding and decoding
isoos/postgresql-dart pull request #130
Opened 2023-09-13 11:13 UTC by simolus3

The Dart SDK, or at least the VM implementation, contains an optimized encoding and decoding pipeline for json to utf8 bytes. By using that instead of chaining the encoders/decoders manually, we can avoid the intermediate strings and make these operations slightly faster.

2023-09-13 14:38 UTC, isoos commented
This will be in direct (long-term) conflict with the configurable encoding feature (#94), wouldn't it?

2023-09-13 22:25 UTC, simolus3 commented
Good point! Since we'd have to move knowledge about the connection encoding into the binary encoder either way for that to work, we could move the `_jsonUtf8` field into there as well and make it a `_jsonText = json.fuse(myEncoding)`. That way we'd preserve the optimization if utf8 is used while still supporting other encodings.

So I think these changes are generally compatible with that feature, although some additional work would be required to fuse the correct codecs then.

2023-09-14 15:27 UTC, isoos requested changes

2023-09-14 15:27 UTC, isoos commented on lib/src/binary_codec.dart
> +          final sink = ByteConversionSink.withCallback((accumulated) {
Let's keep the writer logic.

2023-09-14 16:42 UTC, simolus3 commented on lib/src/binary_codec.dart
> +          final sink = ByteConversionSink.withCallback((accumulated) {
Done

2023-09-23 10:50 UTC, isoos approved these changes

2023-09-23 10:50 UTC, merged